---
title: "fixing_stuff"
author: "Marc David Loeb"
date: '2022-11-16'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(sf)
library(tidyverse)
```


clean
```{r}
tract_1920_study_area <- st_read("data/old_map_data/race_1920_tract_nb.geojson")
tract_1920_study_area <- tract_1920_study_area %>% 
  mutate(id = as.numeric(gsub("[^0-9.-]", "",GISJOIN))) %>%
  mutate_all(~replace(., is.na(.), 0))

st_write(tract_1920_study_area, "data/map_data/race_1920_tract_nb.geojson")
```

clean
```{r}
tract_1930_study_area <- st_read("data/old_map_data/race_1930_tract_nb.geojson")
tract_1930_study_area <- tract_1930_study_area %>% 
  mutate(id = as.numeric(gsub("[^0-9.-]", "",GISJOIN))) %>%
  mutate_all(~replace(., is.na(.), 0))

st_write(tract_1930_study_area, "data/map_data/race_1930_tract_nb.geojson")
```

clean
```{r}
tract_1940_study_area <- st_read("data/old_map_data/race_1940_tract_nb.geojson")
tract_1940_study_area <- tract_1940_study_area %>% 
  mutate(id = as.numeric(gsub("[^0-9.-]", "",GISJOIN))) %>%
  mutate_all(~replace(., is.na(.), 0))

st_write(tract_1940_study_area, "data/map_data/race_1940_tract_nb.geojson")
```

clean
```{r}
tract_1950_study_area <- st_read("data/old_map_data/race_1950_tract_nb.geojson")
tract_1950_study_area <- tract_1950_study_area %>% 
  mutate(id = as.numeric(gsub("[^0-9.-]", "",GISJOIN))) %>%
  mutate_all(~replace(., is.na(.), 0))

st_write(tract_1950_study_area, "data/map_data/race_1950_tract_nb.geojson")
```

```{r}
tract_1970_study_area <- st_read("data/old_map_data/race_1970_tract_nb.geojson")
tract_1970_study_area <- tract_1970_study_area %>% 
  mutate(id = as.numeric(gsub("[^0-9.-]", "",GISJOIN))) %>%
  mutate_all(~replace(., is.na(.), 0))

st_write(tract_1970_study_area, "data/map_data/race_1970_tract_nb.geojson")
```

tract_1960_study_area <- st_read("data/old_map_data/race_1960_tract_nb.geojson")
tract_1960_study_area <- tract_1960_study_area %>% 
  mutate(id = as.numeric(gsub("[^0-9.-]", "",GISJOIN))) %>%
  mutate_all(~replace(., is.na(.), 0))

st_write(tract_1960_study_area, "data/map_data/race_1960_tract_nb.geojson")

```{r}
tract_1980_study_area <- st_read("data/old_map_data/race_1980_tract_nb.geojson")
tract_1980_study_area <- tract_1980_study_area %>% 
  mutate(id = as.numeric(gsub("[^0-9.-]", "",GISJOIN))) %>%
  mutate_all(~replace(., is.na(.), 0))

st_write(tract_1980_study_area, "data/map_data/race_1980_tract_nb.geojson")
```

