---
title: "census_extraction"
author: "Marc David Loeb"
date: '2022-11-15'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(sf)
library(tidyverse)
```


Step 1: Converting csvs of race data and shapefiles of census tract boundaries into geojsons with standardized variable names
Census was inconsistent in 1920s-40s about how to count foreign born whites and non-black people of color. 


1920 tracts
```{r}
###1920s
tract_1920 <-st_read("data/sources/census_shapefiles/us_tract_1920/US_tract_1920_conflated.shp")
st_crs(tract_1920)
#"ESRI 102003, USA_Contiguous_Albers_Equal_Area_Conic
# Switching it to 3857, mercator

# try 3395, which is a different mercator CRS which may actually work
tract_1920 <- st_transform(tract_1920, crs = "EPSG:3857")

#Selecting Cook County Tracts Only
tract_1920 <- tract_1920 %>% 
  select(GISJOIN, STATE, COUNTY, Shape_Area) %>%
  filter(STATE == "17", COUNTY == "031") %>%
  rename(land_area = Shape_Area,
         state = STATE,
         county = COUNTY)

#clean, everything adds up
race_1920 <-read.csv("data/sources/census_csvs/1920_tract.csv") %>% 
  select(-STATE, -STATEA, -COUNTY, -COUNTYA, -AREANAME, -PRETRACTA, -TRACTA, -POSTTRCTA) %>%
  rename(total_pop = A94001,
         nat_white_nat_par = BAT001,
         nat_white_for_par = BAT002,
         nat_white_mix_par = BAT003,
         for_white = BAT004,
         black = BAT005,
         other = BAT006,
         year = YEAR) %>%
  mutate(white = nat_white_nat_par
         +nat_white_for_par
         +nat_white_mix_par
         +for_white, 
         white_per = 100 * white/total_pop,
         black_per = 100 * black/total_pop)

#joining tracts and race data via census tract code
tract_1920 <- left_join(tract_1920, race_1920, by = "GISJOIN")
#fill in missing year values
tract_1920$year = as.numeric("1920")
#add column to be made into id, and fill in na values
tract_1920 <- tract_1920 %>% 
  mutate(id = as.numeric(gsub("[^0-9.-]", "",GISJOIN))) %>%
  mutate_all(~replace(., is.na(.), 0))

plot(tract_1920 %>% select(black_per))
st_write(tract_1920, "data/working_tracts/race_1920_tract.geojson")
```

1930s tracts
```{r}
###1930s
tract_1930 <-st_read("data/sources/census_shapefiles/us_tract_1930/US_tract_1930_conflated.shp")
#st_crs(tract_1930)
#"ESRI 102003, USA_Contiguous_Albers_Equal_Area_Conic
#reprojecting to EPSG:3857, Web Mercator
tract_1930 <- st_transform(tract_1930, crs = "EPSG:3857")

#selecting cook county tracts only
tract_1930 <- tract_1930 %>% 
  select(GISJOIN, STATE, COUNTY, Shape_Area) %>%
  filter(STATE == "17", COUNTY == "031") %>%
  rename(land_area = Shape_Area,
         state = STATE,
         county = COUNTY)
#	G17003100318 has less than total pop
race_1930 <-read.csv("data/sources/census_csvs/1930_tract.csv") %>% 
  select(-STATE, -STATEA, -COUNTY, -COUNTYA, -AREANAME, -PRETRACTA, -TRACTA, -POSTTRCTA) %>%
  rename(total_pop = BHI001,
         nat_white_nat_par = BIQ001,
         nat_white_formix_par = BIQ002,
         for_white = BIQ003,
         black = BIQ004,
         other = BIQ005,
         year = YEAR) %>% 
  mutate(white = nat_white_nat_par
         +nat_white_formix_par
         +for_white, 
         white_per = 100 * white/total_pop,
         black_per = 100 * black/total_pop)
         #total_count = white + black + other,
         #total_per = total_count/total_pop)

tract_1930 <- left_join(tract_1930, race_1930, by = "GISJOIN")
tract_1920$year = as.numeric("1930")
tract_1930 <- tract_1930 %>% 
  mutate(id = as.numeric(gsub("[^0-9.-]", "",GISJOIN))) %>%
  mutate_all(~replace(., is.na(.), 0))

plot(tract_1930 %>% select(black_per))
st_write(tract_1930, "data/working_tracts/race_1930_tract.geojson")
```

1940s tracts
```{r}
###1940s
tract_1940 <-st_read("data/sources/census_shapefiles/us_tract_1940/US_tract_1940_conflated.shp")
st_crs(tract_1940)
#"ESRI 102003, USA_Contiguous_Albers_Equal_Area_Conic
#reprojecting to EPSG:3857, Web Mercator
tract_1940 <- st_transform(tract_1940, crs = "EPSG:3857")

#selecting cook county tracts only
tract_1940 <- tract_1940 %>% 
  select(GISJOIN, STATE, COUNTY, Shape_Area) %>%
  filter(STATE == "17", COUNTY == "031") %>%
  rename(land_area = Shape_Area,
         state = STATE,
         county = COUNTY)

#clean, everything adds up properly
race_1940 <-read.csv("data/sources/census_csvs/1940_tract.csv") %>%
  filter(STATEA == "17", COUNTYA == "31") %>%
  select(-STATE, -STATEA, -COUNTY, -COUNTYA, -AREANAME, -PRETRACTA, -TRACTA, -POSTTRCTA) %>%
  rename(total_pop = BUB001,
         white = BUQ001,
         nonwhite = BUQ002,
         black = BVG001,
         year = YEAR) %>%
  mutate(white_per = 100 * white/total_pop,
         black_per = 100 * black/total_pop)

tract_1940 <- left_join(tract_1940, race_1940, by = "GISJOIN")
tract_1920$year = as.numeric("1940")
tract_1940 <- tract_1940 %>% 
  mutate(id = as.numeric(gsub("[^0-9.-]", "",GISJOIN))) %>%
  mutate_all(~replace(., is.na(.), 0))
plot(tract_1940 %>% select(black_per))
st_write(tract_1940, "data/working_tracts/race_1940_tract.geojson")
```

1950s tracts
```{r}
###1950s
tract_1950 <-st_read("data/sources/census_shapefiles/us_tract_1950/US_tract_1950_conflated.shp")
st_crs(tract_1950)
#"ESRI 102003, USA_Contiguous_Albers_Equal_Area_Conic
#reprojecting to EPSG:3857, Web Mercator
tract_1950 <- st_transform(tract_1950, crs = "EPSG:3857")

#selecting cook county tracts only
tract_1950 <- tract_1950 %>% 
  select(GISJOIN, COUNTY, Shape_Area) %>%
  filter(COUNTY == "031") %>%
  #data is missing state column for some reason
  mutate(state = substr(GISJOIN, 2, 3)) %>%
  filter(state == "17") %>%
  rename(land_area = Shape_Area,
         county = COUNTY)

#clean
race_1950 <-read.csv("data/sources/census_csvs/1950_tract.csv") %>% 
  filter(STATEA == "17", COUNTYA == "31") %>%
  select(-STATE, -STATEA, -COUNTY, -COUNTYA, -AREANAME, -PRETRACTA, -TRACTA, -POSTTRCTA) %>%
  rename(total_pop = BZ8001,
         white = B0J001,
         black = B0J002,
         other_nonwhite = B0J003,
         year = YEAR) %>%
  mutate(white_per = 100 * white/total_pop,
         black_per = 100 * black/total_pop)
         #total_count =  white + black + other_nonwhite,
         #total_per = total_count/total_pop)

tract_1950 <- left_join(tract_1950, race_1950, by = "GISJOIN")
tract_1920$year = as.numeric("1950")
tract_1950 <- tract_1950 %>% 
  mutate(id = as.numeric(gsub("[^0-9.-]", "",GISJOIN))) %>%
  mutate_all(~replace(., is.na(.), 0))
plot(tract_1950 %>% select(black_per))
st_write(tract_1950, "data/working_tracts/race_1950_tract.geojson")
```

1960s tracts
```{r}
###1960s
tract_1960 <-st_read("data/sources/census_shapefiles/us_tract_1960/US_tract_1960_conflated.shp")
st_crs(tract_1960)
#"ESRI 102003, USA_Contiguous_Albers_Equal_Area_Conic
#reprojecting to EPSG:3857, Web Mercator
tract_1960 <- st_transform(tract_1960, crs = "EPSG:3857")

#selecting cook county tracts only
tract_1960 <- tract_1960 %>% 
  select(GISJOIN, STATE, COUNTY, Shape_Area) %>%
  filter(STATE == "17", COUNTY == "031") %>%
  rename(land_area = Shape_Area,
         state = STATE,
         county = COUNTY)

#lots of problems
# race_1960 <-read.csv("data/sources/source_csvs/1960_tract.csv") %>%
#   filter(STATEA == "17", COUNTYA == "31") %>%
#   rename(total_pop = CA4001,
#          white = B7B001,
#          black = B7B002,
#          other = B7B003,
#          year = YEAR) %>%
#   select(GISJOIN, total_pop, white, black, other, year) %>%
#   mutate(white_per = 100 * white/total_pop,
#          black_per = 100 * black/total_pop,
#          total_count = white + black + other,
#          total_per = total_count/total_pop)

#calculating total population from the columns themselves
race_1960 <-read.csv("data/sources/census_csvs/1960_tract.csv") %>%
  filter(STATEA == "17", COUNTYA == "31") %>%
  rename(white = B7B001,
         black = B7B002,
         other = B7B003,
         year = YEAR) %>%
  select(GISJOIN, white, black, other, year) %>%
  mutate(total_pop = white + black + other,
         white_per = 100 * white/total_pop,
         black_per = 100 * black/total_pop)

tract_1960 <- left_join(tract_1960, race_1960, by = "GISJOIN")
tract_1920$year = as.numeric("1960")
tract_1960 <- tract_1960 %>% 
  mutate(id = as.numeric(gsub("[^0-9.-]", "",GISJOIN))) %>%
  mutate_all(~replace(., is.na(.), 0))
plot(tract_1960 %>% select(black_per))
st_write(tract_1960, "data/working_tracts/race_1960_tract.geojson")
```

1970s tracts
```{r}
###1970s
tract_1970 <-st_read("data/sources/census_shapefiles/us_tract_1970/US_tract_1970_conflated.shp")
st_crs(tract_1970)
#"ESRI 102003, USA_Contiguous_Albers_Equal_Area_Conic
#reprojecting to EPSG:3857, Web Mercator
tract_1970 <- st_transform(tract_1970, crs = "EPSG:3857")

#selecting cook county tracts only
tract_1970 <- tract_1970 %>% 
  select(GISJOIN, COUNTY, Shape_Area) %>%
  filter(COUNTY == "031") %>%
  #data is missing state column for some reason
  mutate(state = substr(GISJOIN, 2, 3)) %>%
  filter(state == "17") %>%
  rename(land_area = Shape_Area,
         county = COUNTY)

#there are no tracts where the black population exceeds 100%
race_1970 <-read.csv("data/sources/census_csvs/1970_tract.csv") %>%
  filter(STATEA == "17", COUNTYA == "31") %>%
  rename(total_pop = CY7001,
         black = CY8001,
         year = YEAR) %>%
  select(GISJOIN, total_pop, black, year) %>%
  mutate(black_per = 100 * black/total_pop)
         #pop_diff = total_pop - black)

tract_1970 <- left_join(tract_1970, race_1970, by = "GISJOIN")
tract_1920$year = as.numeric("1970")
tract_1970 <- tract_1970 %>% 
  mutate(id = as.numeric(gsub("[^0-9.-]", "",GISJOIN))) %>%
  mutate_all(~replace(., is.na(.), 0))
plot(tract_1970 %>% select(black_per))
st_write(tract_1970, "data/working_tracts/race_1970_tract.geojson")
```

1980s tracts
```{r}
###1980s
tract_1980 <-st_read("data/sources/census_shapefiles/us_tract_1980/US_tract_1980_conflated.shp")
st_crs(tract_1980)
#"ESRI 102003, USA_Contiguous_Albers_Equal_Area_Conic
#reprojecting to EPSG:3857, Web Mercator
tract_1980 <- st_transform(tract_1980, crs = "EPSG:3857")

#selecting cook county tracts only
tract_1980 <- tract_1980 %>% 
  select(GISJOIN, COUNTY, Shape_Area) %>%
  filter(COUNTY == "031") %>%
  #data is missing state column for some reason
  mutate(state = substr(GISJOIN, 2, 3)) %>%
  filter(state == "17") %>%
  rename(land_area = Shape_Area,
         county = COUNTY)

#clean
race_1980 <-read.csv("data/sources/census_csvs/1980_tract.csv") %>%
  filter(STATEA == "17", COUNTYA == "31") %>%
  rename(total_pop = C6W001,
         white = C6X001,
         black = C6X002,
         native = C6X003,
         asian = C6X004,
         other = C6X005,
         year = YEAR) %>%
  select(GISJOIN, total_pop, white, black, native, asian, other, year) %>%
  mutate(white_per = 100 * white/total_pop,
         black_per = 100 * black/total_pop)
         #total_count = white + black + native + asian + other,
         #total_per = total_count/total_pop)

tract_1980 <- left_join(tract_1980, race_1980, by = "GISJOIN")
tract_1920$year = as.numeric("1980")
tract_1980 <- tract_1980 %>% 
  mutate(id = as.numeric(gsub("[^0-9.-]", "",GISJOIN))) %>%
  mutate_all(~replace(., is.na(.), 0))
plot(tract_1980 %>% select(black_per))
st_write(tract_1980, "data/working_tracts/race_1980_tract.geojson")
```
